# Generated by Django 3.1.7 on 2023-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20231011_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
